# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://adityatelange.github.io/hugo-PaperMod/"
title: Sara DM
copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
paginate: 5
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "EN"
    weight: 1
    taxonomies:
      archive: archives
      category: categories
      tag: tags
      series: series
      search: search
    menu:
      main:
        - name: Search
          url: search
          weight: 1
        - name: Tags
          url: tags
          weight: 2
    params:
      languageAltTitle: English
      profileMode:
        enabled: true
        title: Sara DM
        imageUrl: "https://avatars.githubusercontent.com/u/19250102?v=4"
        imageTitle: Image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "Fullstack Developer"
        buttons:
          - name: Blog
            url: posts
          # disable profileMode to show this
      homeInfoParams:
        Title: "Iep! 👋"
        Content: "### A bit about me\n
        # &nbsp; \n
        - <span class='emoji'>👾</span> - Fullstack Developer \n
        - <span class='emoji'>☕️</span> - Fluent in English and Catalan <span class='emoji'>✌️</span> \n 
         - <span class='emoji'>🤝</span> - Skilled in teamwork \n 
        - <span class='emoji'>🔎</span> - Interested in cybersecurity, programming languages and scalable architectures \n
        # &nbsp; \n
        Read you around! \n
        ## &nbsp; \n
        "

  es:
    languageName: "ES"
    weight: 2
    taxonomies:
      archive: archive
      category: categories
      tag: tags
      search: search
    menu:
      main:
        - name: Buscar
          url: search
          weight: 1
        - name: Etiquetas
          url: tags
          weight: 2

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: Spanish
      profileMode:
        enabled: true
        title: Sara DM
        imageUrl: "https://avatars.githubusercontent.com/u/19250102?v=4"
        imageTitle: Image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "Fullstack Developer"
        buttons:
          - name: Blog
            url: posts
      # disable profileMode to show this
      homeInfoParams:
        Title: "Iep! 👋"
        Content: "### Sobre mí\n
        # &nbsp; \n
         - <span class='emoji'>👾</span> - Soy fullstack \n
        - <span class='emoji'>☕️</span> - Con un buen nivel de inglés (aunque no he querido traducir lo anterior) y catalán <span class='emoji'>✌️</span> \n 
         - <span class='emoji'>🤝</span> - Trabajo bien en equipo \n 
        - <span class='emoji'>🔎</span> - Me interesan la ciberseguridad, los lenguajes de programación y la arquitectura escalable \n
        # &nbsp; \n
        Nos leemos! \n
        ## &nbsp; \n
        "

outputs:
  home:
    - HTML
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Sara DM's homepage"
  author: ["Sara DM", "Theme PaperMod"]
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: ["images/ios-shortcuts-alarms.jpg"]

  socialIcons:
    - name: github
      title: GitHub
      url: "https://github.com/Kaylen7"
    - name: bluesky
      title: BlueSky
      url: "https://bsky.app/profile/sara-dm.bsky.social"
    - name: linkedin
      title: Reach out in LinkedIn
      url: "https://www.linkedin.com/in/saradomenechm/"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

ShareButtons:
  twitter: false